/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#define MCU_ACT_AS_MASTER

//#define MCU_ACT_AS_SLAVE


#include "stdint.h"
#include "stdio.h"
#include "stdlib.h"

#include "Stm32_f103_c6_GPIO_Driver.h"
#include "Stm32_f103_c6.h"
#include "keybad.h"
#include "lcd.h"
#include "Stm32_f103_c6_EXTI_Driver.h"
#include "Stm32_f103_c6_USART_Driver.h"
#include "Stm32_f103_c6_SPI_Driver.h"






void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++)
	{

		for(j=0;j<255;j++);
	}


}

void Clk_Init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

}




unsigned char ch;

void Hussein_IRQ_Callback(void)
{
	MCAL_UART_ReceiveData(USART1, (uint16_t*) &ch, disable);
	MCAL_UART_SendData(USART1,(uint16_t*) &ch, enable);

	//send to SPI
#ifdef MCU_ACT_AS_MASTER

	MCAL_GPIO_WRITE_PIN(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1,(uint16_t*) &ch, pollingEnable);
	MCAL_GPIO_WRITE_PIN(GPIOA, GPIO_PIN_4, 1);
#endif






}
int main(void)
{
	USART_Coinf uartCFG;
	GPIO_PinConfig_t PinConfig;

	Clk_Init();

	//===================UART INIT==============================
	uartCFG.BaudRate = USART_BaudRate_115200;
	uartCFG.HWFlowCTL = USART_HWFLOWCTL_NONE;
	uartCFG.IRQ_ENABLE = USART_IRQ_ENABLE_RXNEIE;
	uartCFG.P_IRQ_CALLBACK = Hussein_IRQ_Callback;
	uartCFG.Parity = USART_Parity_NONE;
	uartCFG.PayLoadLenght = USART_PayLoad_Length_8B;
	uartCFG.StopBits = USART_STOP_ONE;
	uartCFG.USART_Mode =USART_Mode_TX_RX;
	MCAL_UART_Init(USART1,&uartCFG);
	MCAL_UART_GPIO_Set_Pins(USART1);


	//======================SPI INIT=============================
	SPI_Config SPI1_Coinfig;

	//common configurations

	SPI1_Coinfig.CLKPhase = SPI_CLKPhase_2ndEDGE_First_data_capture;
	SPI1_Coinfig.CLKPolarity = SPI_CLKPolarity_high_when_idel;
	SPI1_Coinfig.Data_Size = SPI_DataSize_8Bit;
	SPI1_Coinfig.Frame_Format = SPI_FrameFormat_MSB_Transmitted_First;
	//ASUME CLK 8MHZ
	SPI1_Coinfig.SPI_BAUDRATE_PRECALER = BAUDRATE_PRECALER_8;
	SPI1_Coinfig.Comunication_Mode = SPI_direction_2Line;

#ifdef MCU_ACT_AS_MASTER

	SPI1_Coinfig.Device_Mode = SPI_Device_Mode_Master;
	SPI1_Coinfig.P_IRQ_CallBack = NULL;
	SPI1_Coinfig.NSS = SPI_NSS_Software_Set;
	SPI1_Coinfig.IRQ_Enable = SPI_IRQ_ENABLE_NONE;

#endif

	MCAL_SPI_Init(SPI1,&SPI1_Coinfig);
	MCAL_SPI_GPIO_SET_PINS(SPI1);


	//configure SS by GPIOA PORT4
	PinConfig.GPIO_PinNumber = GPIO_PIN_4;
	PinConfig.GPIO_Mode = GPIO_MODE_output_push_pull;
	PinConfig.GPIO_SPEED_OUT = GPIO_SPEED_10MHZ;
	MCAL_GPIO_INIT(GPIOA, &PinConfig);


	//force the slave slect "high" ide mode

	MCAL_GPIO_WRITE_PIN(GPIOA, GPIO_PIN_4, 1);





	while (1)
	{

	}




}









