/*
 * Stm32_f103_c6_EXTI_Drivers.h
 *
 *  Created on: Sep 18, 2023
 *      Author: Hussein Sabry
 */

#ifndef INCLUDE_STM32_F103_C6_EXTI_DRIVER_H_
#define INCLUDE_STM32_F103_C6_EXTI_DRIVER_H_


// includes

#include "Stm32_f103_c6.h"
#include "Stm32_f103_c6_GPIO_Driver.h"


//--------------------------


typedef struct
{
	uint16_t         ETI_InputLineNumber;
	GPIO_Type_Def*   GPIO_Port;
	uint16_t         GPIO_PIN;
	uint8_t          IVT_IRQ_NUMBER;


}EXTI_GPIO_Maping;

typedef struct
{
	EXTI_GPIO_Maping EXTI_PIN;          //Specified External interrupt GPIO Maping
	                                   //this parameter must be set based on @ref EXTI_Define
	uint8_t          Trigger_Case ;   //Specified RAISING or FALLING case  or BOTH TRIGGER
                                     //this parameter must be set based on @ref EXTI_TRIGGER_Define

	uint8_t          IRQ_EN;        //enable or disable the EXTI IQR (IT will enable the IQR Musk and also NVIC)
	                               //this parameter must be set based on @ref EXTI_TRQ_Define

	void (*p_TRQ_CALLBACK)(void); //this fuction will be called once the IQR happened


}EXTI_PinConf_t;


//MACROS Configuration

//@ref EXTI_define

#define EXTI0  0
#define EXTI1  1
#define EXTI2  2
#define EXTI3  3
#define EXTI4  4
#define EXTI5  5
#define EXTI6  6
#define EXTI7  7
#define EXTI8  8
#define EXTI9  9
#define EXTI10 10
#define EXTI11 11
#define EXTI12 12
#define EXTI13 13
#define EXTI14 14
#define EXTI15 15







//EXTI0
#define EXTI0PA0  (EXTI_GPIO_Maping){EXTI0,GPIOA,GPIO_PIN_0,EXTI0_IQR}
#define EXTI0PB0  (EXTI_GPIO_Maping){EXTI0,GPIOB,GPIO_PIN_0,EXTI0_IQR}
#define EXTI0PC0  (EXTI_GPIO_Maping){EXTI0,GPIOC,GPIO_PIN_0,EXTI0_IQR}
#define EXTI0PD0  (EXTI_GPIO_Maping){EXTI0,GPIOD,GPIO_PIN_0,EXTI0_IQR}

//EXTI1
#define EXTI1PA1  (EXTI_GPIO_Maping){EXTI1,GPIOA,GPIO_PIN_1,EXTI1_IQR}
#define EXTI1PB1  (EXTI_GPIO_Maping){EXTI1,GPIOB,GPIO_PIN_1,EXTI1_IQR}
#define EXTI1PC1  (EXTI_GPIO_Maping){EXTI1,GPIOC,GPIO_PIN_1,EXTI1_IQR}
#define EXTI1PD1  (EXTI_GPIO_Maping){EXTI1,GPIOD,GPIO_PIN_1,EXTI1_IQR}

//EXTI2
#define EXTI2PA2  (EXTI_GPIO_Maping){EXTI2,GPIOA,GPIO_PIN_2,EXTI2_IQR}
#define EXTI2PB2  (EXTI_GPIO_Maping){EXTI2,GPIOB,GPIO_PIN_2,EXTI2_IQR}
#define EXTI2PC2  (EXTI_GPIO_Maping){EXTI2,GPIOC,GPIO_PIN_2,EXTI2_IQR}
#define EXTI2PD2  (EXTI_GPIO_Maping){EXTI2,GPIOD,GPIO_PIN_2,EXTI2_IQR}

//EXTI3
#define EXTI3PA3  (EXTI_GPIO_Maping){EXTI3,GPIOA,GPIO_PIN_3,EXTI3_IQR}
#define EXTI3PB3  (EXTI_GPIO_Maping){EXTI3,GPIOB,GPIO_PIN_3,EXTI3_IQR}
#define EXTI3PC3  (EXTI_GPIO_Maping){EXTI3,GPIOC,GPIO_PIN_3,EXTI3_IQR}
#define EXTI3PD3  (EXTI_GPIO_Maping){EXTI3,GPIOD,GPIO_PIN_3,EXTI3_IQR}

//EXTI4
#define EXTI4PA4  (EXTI_GPIO_Maping){EXTI4,GPIOA,GPIO_PIN_4,EXTI4_IQR}
#define EXTI4PB4  (EXTI_GPIO_Maping){EXTI4,GPIOB,GPIO_PIN_4,EXTI4_IQR}
#define EXTI4PC4  (EXTI_GPIO_Maping){EXTI4,GPIOC,GPIO_PIN_4,EXTI4_IQR}
#define EXTI4PD4  (EXTI_GPIO_Maping){EXTI4,GPIOD,GPIO_PIN_4,EXTI4_IQR}

//EXTI5
#define EXTI5PA5  (EXTI_GPIO_Maping){EXTI5,GPIOA,GPIO_PIN_5,EXTI5_IQR}
#define EXTI5PB5  (EXTI_GPIO_Maping){EXTI5,GPIOB,GPIO_PIN_5,EXTI5_IQR}
#define EXTI5PC5  (EXTI_GPIO_Maping){EXTI5,GPIOC,GPIO_PIN_5,EXTI5_IQR}
#define EXTI5PD5  (EXTI_GPIO_Maping){EXTI5,GPIOD,GPIO_PIN_5,EXTI5_IQR}

//EXTI6
#define EXTI6PA6  (EXTI_GPIO_Maping){EXTI6,GPIOA,GPIO_PIN_6,EXTI6_IQR}
#define EXTI6PB6  (EXTI_GPIO_Maping){EXTI6,GPIOB,GPIO_PIN_6,EXTI6_IQR}
#define EXTI6PC6  (EXTI_GPIO_Maping){EXTI6,GPIOC,GPIO_PIN_6,EXTI6_IQR}
#define EXTI6PD6  (EXTI_GPIO_Maping){EXTI6,GPIOD,GPIO_PIN_6,EXTI6_IQR}

//EXTI7
#define EXTI7PA7  (EXTI_GPIO_Maping){EXTI7,GPIOA,GPIO_PIN_7,EXTI7_IQR}
#define EXTI7PB7  (EXTI_GPIO_Maping){EXTI7,GPIOB,GPIO_PIN_7,EXTI7_IQR}
#define EXTI7PC7  (EXTI_GPIO_Maping){EXTI7,GPIOC,GPIO_PIN_7,EXTI7_IQR}
#define EXTI7PD7  (EXTI_GPIO_Maping){EXTI7,GPIOD,GPIO_PIN_7,EXTI7_IQR}

//EXTI8
#define EXTI8PA8  (EXTI_GPIO_Maping){EXTI8,GPIOA,GPIO_PIN_8,EXTI8_IQR}
#define EXTI8PB8  (EXTI_GPIO_Maping){EXTI8,GPIOB,GPIO_PIN_8,EXTI8_IQR}
#define EXTI8PC8  (EXTI_GPIO_Maping){EXTI8,GPIOC,GPIO_PIN_8,EXTI8_IQR}
#define EXTI8PD8  (EXTI_GPIO_Maping){EXTI8,GPIOD,GPIO_PIN_8,EXTI8_IQR}

//EXTI9
#define EXTI9PA9  (EXTI_GPIO_Maping){EXTI9,GPIOA,GPIO_PIN_9,EXTI9_IQR}
#define EXTI9PB9  (EXTI_GPIO_Maping){EXTI9,GPIOB,GPIO_PIN_9,EXTI9_IQR}
#define EXTI9PC9  (EXTI_GPIO_Maping){EXTI9,GPIOC,GPIO_PIN_9,EXTI9_IQR}
#define EXTI9PD9  (EXTI_GPIO_Maping){EXTI9,GPIOD,GPIO_PIN_9,EXTI9_IQR}

//EXTI10
#define EXTI10PA10  (EXTI_GPIO_Maping){EXTI10,GPIOA,GPIO_PIN_10,EXTI10_IQR}
#define EXTI10PB10  (EXTI_GPIO_Maping){EXTI10,GPIOB,GPIO_PIN_10,EXTI10_IQR}
#define EXTI10PC10  (EXTI_GPIO_Maping){EXTI10,GPIOC,GPIO_PIN_10,EXTI10_IQR}
#define EXTI10PD10  (EXTI_GPIO_Maping){EXTI10,GPIOD,GPIO_PIN_10,EXTI10_IQR}

//EXTI11
#define EXTI11PA11  (EXTI_GPIO_Maping){EXTI11,GPIOA,GPIO_PIN_11,EXTI11_IQR}
#define EXTI11PB11  (EXTI_GPIO_Maping){EXTI11,GPIOB,GPIO_PIN_11,EXTI11_IQR}
#define EXTI11PC11  (EXTI_GPIO_Maping){EXTI11,GPIOC,GPIO_PIN_11,EXTI11_IQR}
#define EXTI11PD11  (EXTI_GPIO_Maping){EXTI11,GPIOD,GPIO_PIN_11,EXTI11_IQR}
//EXTI12
#define EXTI12PA12  (EXTI_GPIO_Maping){EXTI12,GPIOA,GPIO_PIN_12,EXTI12_IQR}
#define EXTI12PB12  (EXTI_GPIO_Maping){EXTI12,GPIOB,GPIO_PIN_12,EXTI12_IQR}
#define EXTI12PC12  (EXTI_GPIO_Maping){EXTI12,GPIOC,GPIO_PIN_12,EXTI12_IQR}
#define EXTI12PD12  (EXTI_GPIO_Maping){EXTI12,GPIOD,GPIO_PIN_12,EXTI12_IQR}

//EXTI13
#define EXTI13PA13  (EXTI_GPIO_Maping){EXTI13,GPIOA,GPIO_PIN_13,EXTI13_IQR}
#define EXTI13PB13  (EXTI_GPIO_Maping){EXTI13,GPIOB,GPIO_PIN_13,EXTI13_IQR}
#define EXTI13PC13  (EXTI_GPIO_Maping){EXTI13,GPIOC,GPIO_PIN_13,EXTI13_IQR}
#define EXTI13PD13  (EXTI_GPIO_Maping){EXTI13,GPIOD,GPIO_PIN_13,EXTI13_IQR}

//EXTI14
#define EXTI14PA14  (EXTI_GPIO_Maping){EXTI14,GPIOA,GPIO_PIN_14,EXTI14_IQR}
#define EXTI14PB14  (EXTI_GPIO_Maping){EXTI14,GPIOB,GPIO_PIN_14,EXTI14_IQR}
#define EXTI14PC14  (EXTI_GPIO_Maping){EXTI14,GPIOC,GPIO_PIN_14,EXTI14_IQR}
#define EXTI14PD14  (EXTI_GPIO_Maping){EXTI14,GPIOD,GPIO_PIN_14,EXTI14_IQR}

//EXTI15
#define EXTI15PA15  (EXTI_GPIO_Maping){EXTI15,GPIOA,GPIO_PIN_15,EXTI15_IQR}
#define EXTI15PB15  (EXTI_GPIO_Maping){EXTI15,GPIOB,GPIO_PIN_15,EXTI15_IQR}
#define EXTI15PC15  (EXTI_GPIO_Maping){EXTI15,GPIOC,GPIO_PIN_15,EXTI15_IQR}
#define EXTI15PD15  (EXTI_GPIO_Maping){EXTI15,GPIOD,GPIO_PIN_15,EXTI15_IQR}


//@ref EXTI_TRIGGER_Define
#define EXTI_Trigger_RISING              0
#define EXTI_Trigger_FALLING             1
#define EXTI_Trigger_RisingAndFalling    2

//@ref EXTI_TRQ_Define

#define EXTI_TRQ_ENABLE                  1
#define EXTI_TRQ_DISABLE                 0





//===============API SUPPORTED BY MCAL GPIO DRIVER===================

void MCAL_EXTI_GPIO_INIT   (EXTI_PinConf_t* EXTI_Config);

void MCAL_EXTI_GPIO_UPDATE (EXTI_PinConf_t* EXTI_Config);

void MCAL_EXTI_GPIO_DEINIT (void);














#endif
